#!/bin/bash
echo "Updating OpenVas Feeds"
openvas-nvt-sync
openvas-scapdata-sync
openvas-certdata-sync

wget http://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xml -O service-names-port-numbers.xml
openvas-portnames-update /tmp/service-names-port-numbers.xml
